---
galaxy_info:
  author: Bogdan Socaciu
  description: Ansible role to install and config Java
  company: "Revian Labs"
  license: "MIT"
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
    - bionic
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - java
    - openjdk
    - jdk
dependencies: []
