apiVersion: v1
kind: Service
metadata:
  name: devops-webapp-sample
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: devops-webapp-sample
  type: NodePort